"""
clean_woodmart_settings.py

One-off utility: reads plugin/woodmart_settings_report (1).txt, strips all
shop-specific Value: lines, keeps setting IDs, Labels, Types, Descriptions,
and Defaults. Writes a generic reference doc to
woo-agent/plugin_docs/woodmart-settings-reference.md.
"""
from __future__ import annotations

import re
from pathlib import Path


INPUT_PATH = Path(__file__).parent.parent / "plugin" / "woodmart_settings_report (1).txt"
OUTPUT_PATH = Path(__file__).parent / "plugin_docs" / "woodmart-settings-reference.md"

HEADER_COMMENT = """\
# Woodmart Theme Settings — Generic Reference

This file is auto-generated by `clean_woodmart_settings.py`.
It lists every Woodmart theme option with its ID, label, type, description,
and default value. Shop-specific current values have been removed so this
document works as a reference for ALL shops.

---

"""

# Lines to drop entirely (header metadata + all Value: lines)
SKIP_PREFIXES = (
    "# Generated:",
    "# Total settings",
    "# How to read",
    "# Woodmart Theme Settings - Current Configuration",
    "# If 'Current Value'",
)

VALUE_LINE_RE = re.compile(r"^\s+Value:\s")


def is_skippable(line: str) -> bool:
    stripped = line.rstrip()
    if VALUE_LINE_RE.match(line):
        return True
    for prefix in SKIP_PREFIXES:
        if stripped.startswith(prefix):
            return True
    return False


def collapse_blank_lines(lines: list[str]) -> list[str]:
    """Reduce consecutive blank lines to at most one."""
    result: list[str] = []
    prev_blank = False
    for line in lines:
        is_blank = line.strip() == ""
        if is_blank and prev_blank:
            continue
        result.append(line)
        prev_blank = is_blank
    return result


def clean(input_path: Path, output_path: Path) -> None:
    raw = input_path.read_text(encoding="utf-8")
    lines = raw.splitlines(keepends=True)

    filtered = [line for line in lines if not is_skippable(line)]
    collapsed = collapse_blank_lines(filtered)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as fh:
        fh.write(HEADER_COMMENT)
        fh.writelines(collapsed)

    value_count = sum(1 for ln in lines if VALUE_LINE_RE.match(ln))
    kept_count = len(collapsed)
    print(f"Input : {len(lines):>6} lines")
    print(f"Dropped Value: lines : {value_count:>6}")
    print(f"Output: {kept_count:>6} lines -> {output_path}")


if __name__ == "__main__":
    clean(INPUT_PATH, OUTPUT_PATH)
